name: CMake

on: [push, pull_request]

env:
  VITASDK: /usr/local/vitasdk

jobs:
  # build-windows:
  #   name: Windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: Install dependencies
  #       run: |

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install git gcc make cmake libsdl2-dev libjsoncpp-dev -y

      - name: Build project
        run: |
          git clone https://github.com/sand-box2d/sand-box2d
          cd sand-box2d
          git submodule update --init --depth=1
          mkdir build
          cd build
          cmake .. -DBUILD_LINUX=ON
          make -j4

      - name: Output build
        uses: actions/upload-artifact@v4
        with:
          name: Linux executable
          path: |
            sand-box2d/build/Sand-Box2D
            sand-box2d/build/assets
