name: CMake

on: [push, pull_request]

env:
  VITASDK: /usr/local/vitasdk

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install cmake libsdl2-dev libjsoncpp-dev -y

      - name: Build project
        run: |
          git clone https://github.com/sand-box2d/sand-box2d
          cd sand-box2d
          git submodule update --init --depth=1
          mkdir build
          cd build
          cmake .. -DBUILD_LINUX=ON
          make -j4

      - name: Output build
        uses: actions/upload-artifact@v4
        with:
          name: sb2d-linux
          path: |
            sand-box2d/build/Sand-Box2D
            sand-box2d/build/assets

  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: |
          brew install sdl2 jsoncpp

      - name: Build project
        run: |
          git clone https://github.com/sand-box2d/sand-box2d
          cd sand-box2d
          git submodule update --init --depth=1
          mkdir build
          cd build
          cmake .. -DBUILD_MACOS=ON
          make -j4

      - name: Output build
        uses: actions/upload-artifact@v4
        with:
          name: sb2d-macos
          path: |
            sand-box2d/build/Sand-Box2D
            sand-box2d/build/assets

  build-vita:
    name: PS Vita
    runs-on: ubuntu-latest

    steps:
      - name: Install Vita SDK
        continue-on-error: true
        run: |
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          ./bootstrap-vitasdk.sh
          ./install-all.sh

      - name: Build project
        run: |
          git clone https://github.com/sand-box2d/sand-box2d
          cd sand-box2d
          git submodule update --init --depth=1
          mkdir build
          cd build
          cmake .. -DBUILD_VITA=ON -Wno-deprecated
          make -j4

      - name: Output build
        uses: actions/upload-artifact@v4
        with:
          name: sb2d-vita
          path: |
            sand-box2d/build/*.vpk
 