name: macOS

on: [push, pull_request]

jobs:
  build:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: |
          brew install sdl2 jsoncpp

      - name: Build project
        run: |
          git clone https://github.com/sand-box2d/sand-box2d
          cd sand-box2d
          git submodule update --init --depth=1
          mkdir build
          cd build
          cmake .. -DBUILD_MACOS=ON
          make -j4

      - name: Output build
        uses: actions/upload-artifact@v4
        with:
          name: sb2d-macos
          path: |
            sand-box2d/build/Sand-Box2D
            sand-box2d/build/assets
